#!/bin/bash
INSTALL=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
export DYNAWO_INSTALL_DIR=$INSTALL/external/dynawo
export LD_LIBRARY_PATH=$INSTALL/lib64:$DYNAWO_INSTALL_DIR/lib:$LD_LIBRARY_PATH
export IIDM_XML_XSD_PATH=$DYNAWO_INSTALL_DIR/share/iidm/xsd
export DYNAFLOW_LAUNCHER_LOCALE=en_GB
export DYNAFLOW_LAUNCHER_INSTALL=$INSTALL
export DYNAWO_RESOURCES_DIR=$DYNAWO_INSTALL_DIR/share:$DYNAWO_INSTALL_DIR/share/xsd
export DYNAWO_DDB_DIR=$DYNAWO_INSTALL_DIR/ddb
export DYNAWO_IIDM_EXTENSION=$DYNAWO_INSTALL_DIR/lib/libdynawo_DataInterfaceIIDMExtension.so
export DYNAWO_LIBIIDM_EXTENSIONS=$DYNAWO_INSTALL_DIR/lib

$INSTALL/bin/DynaFlowLauncher $@
